version: '3'
services:
  web:
    build:
      context: ./ # Punto al directorio actual
      dockerfile: nginx.Dockerfile # Ruta al Dockerfile de Nginx
    ports:
      - "80:80"

  api:
    build: ./api
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - api-data:/app/data

  mongo:
    build:
      context: . # Punto al directorio actual
      dockerfile: Dockerfile # Ruta al Dockerfile de MongoDB (si has renombrado)
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  api-data:
  mongo-data:
